import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Link from "next/link"; // Unused import
import Sidebar from "../components/Sidebar";
import TopBar from "../components/TopBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Sidebar open/close state (client only)
  // Use a workaround for SSR: sidebar is always open on first render
  // For a real app, move this to a client component
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <div className="flex flex-col min-h-screen">
          {/* Full-width top bar */}
          <TopBar />
          
          <div className="flex flex-1 min-h-0 overflow-hidden">
            {/* Sidebar */}
            <Sidebar />
            {/* Main content */}
            <div className="relative flex-1 min-h-0 overflow-hidden">
              <main className="flex flex-col flex-1 min-h-0 bg-black text-white border-l border-white/20 overflow-hidden">
                {children}
              </main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
